---
title: "Volcano Plot"
author: "Aleksandra Dohren"
date: '2022-06-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#alles aus exp2_unique raus ( alle Gene und die erste Spalte)
```{r}
#the dataset I will be working with; zEile 154 aus RMD REport; here is the lsit of top diff. Expr Genes
load('~/GitHub/project/VolcanoData.RData')
View(VolcanoData)

```
```{r}
library(org.Mm.eg.db)
VolcanoData.df <- as.data.frame(VolcanoData)
#converting ENSEMBLID to Gene Symbol (Mouse)
VolcanoData.df <- mapIds(org.Mm.eg.db, keys = rownames(VolcanoData.df), keytype = "ENSEMBL", column ="SYMBOL", multiVals="first")
VolcanoData.df
#matchen mit datadr/ name und symbol als Rownames/ 
```
```{r}
#Volcanoploots:
library(EnhancedVolcano)
```


Cell staged 4, 8 under und overexpressed genes
```{r}
#PLot on 4/8 cell stages in DGE
load('~/GitHub/project/fit_matched2.RData')

Volcano = topTable(fit_matched2, number = 92820, coef = 1)
EnhancedVolcano(Volcano, x = "logFC", y ="adj.P.Val", lab = rownames(Volcano),
                subtitle = 'Significance = 5%',pCutoff = 0.05, pointSize = 1, ylim = c(0, 10.5))


```


bovine Chips

```{r}
library(affy)
library(vsn)
library(AnnotationDbi)
library(cluster)
library(dplyr)
library(hexbin)
library(pheatmap)
library(rstudioapi)
library(tidyverse)
library(readr)
library(ggplot2)
library(knitr)
library(limma)
library(Rcpp)
library(icd.data)
library(tibble)
library(bovgene10stbtenstprobe)
library(bovgene10stbtenstcdf)
library(bovgene11stbtenstprobe)
library(bovgene11stbtenstcdf)
library(bovinebtenstcdf)
library(bovinebtenstprobe)
library(biomaRt)

```

Setting project path
```{r}
projectPath <- dirname(rstudioapi::getSourceEditorContext()$path)
```

```{r}
setwd(paste(projectPath,"rawdata","zippedbovine",sep = "/"))
data.bovine=ReadAffy()
Data.bovine=data.bovine@cdfName <- "Bovine_Bt_ENST"

```

```{r}
for (i in 1:16){
   image(data.bovine[,i], col = rainbow (100, start = 0, end = 0.75)[100:1])}
```


```{r}
bovine_RNAdeg <- AffyRNAdeg(data.bovine)
plotAffyRNAdeg(bovine_RNAdeg, col = rainbow(16))
```


```{r}
set.seed(234)
vsnbovine <- vsnrma(data.bovine)
meanSdPlot(vsnbovine, plot = FALSE)$gg + theme(aspect.ratio = 1)
vsn.bovine = exprs(vsnbovine)
```


```{r}
## Before normalization
par ( las =2)
boxplot (data.bovine ,col = rainbow (150),cex.axis = 0.4,main ="Gene expression bovine embryonic development before normalization")

## After normalization
par ( las =2)
boxplot (vsn.bovine,col = rainbow (150),cex.axis =0.5,main ="Gene expression bovine embryonic development after normalization")
```

```{r}
## Before normalization
par(mai = c(0.9,0.9,0.9,0.5))
hist(data.bovine, col = rainbow(10), main = "Density function of log intensity bovine ED before normalization")

## After normalization
par(mai = c(0.9,0.9,0.9,0.5))
plot(density(vsn.bovine), type = "n", xlab = "log Intensity", ylim = c(0, 0.6),main = "Density function of log intensity bovine ED after normalization")
for (i in 1:ncol(vsn.bovine)){lines(density(vsn.bovine[,i]), col = rainbow(10)[i])}
```

hier dann das df ohne Controllchips erstellen:

```{r}
data_ohneaffxbovine= vsn.bovine[113:17520,]
namen = strsplit(rownames(data_ohneaffxbovine), split = '.', fixed = TRUE)
namen = sapply(namen , FUN = function(x){return(x[1])})
rownames(data_ohneaffxbovine) <- namen
data_ohneaffxbovine
```


jetzt GeneID in Genesymbols umwandeln:


```{r}
mart = useEnsembl(dataset = "btaurus_gene_ensembl", biomart='ensembl')
getgenename = function(gene){

res = getBM(attributes = c("ensembl_gene_id", "external_gene_name"),
            filters = "ensembl_gene_id",
            values = gene,
            mart = mart )
message('Let me check that for you :D')

return(res)
}

getgenename(namen[1])

```

```{r}
#BiocManager::install("org.Bt.eg.db")
#BiocManager::install("clusterProfiler")
library(org.Bt.eg.db)
columns(org.Bt.eg.db)
symbols = select(org.Bt.eg.db, keys = keys(org.Bt.eg.db), columns = c('ENSEMBLTRANS', 'SYMBOL'))  
symbols = na.omit(symbols)
BovineGeneSymbols = symbols[match(namen, symbols$ENSEMBLTRANS), 2:3]


```


















hier als backup weil es am Ende wieder nich klappt:
```{r}
setwd(paste(projectPath,"rawdata","zippedbovine",sep = "/"))
data.bovine=ReadAffy(celfile.path = "C:/Users/Aleksandra/Documents/GitHub/project/rawdata/zippedbovine")
Data.bovine=data.bovine@cdfName <- "Bovine_Bt_ENST"
view(Data.bovine)
```




